#!/bin/bash

red='\033[0;31m'
nc='\033[0m' # No Color

for d in test/*/ ; do
  input="${d}input.lucy"
  output="${d}expected.js"

  tmp=$(mktemp)

  node ./scripts/run_compile.mjs < $input > $tmp
  
  d=$(diff $output $tmp | colordiff)

  if [ ${#d} -ge 1 ]; then
    echo -e "${red}FAILED${nc} - $input"
    echo ""
    echo "$d"
  fi
done