#!/bin/bash

LC=bin/lc
ret=0

run_test() {
  d=$1

  input="${d}input.lucy"
  output="${d}expected.js"

  tmp=$(mktemp)

  #node ./scripts/run_compile.mjs < $input > $tmp
  $LC $input > $tmp

  if [ ! -f $output ]; then
      mv $tmp $output
      return
  fi
  
  d=$(diff $output $tmp | colordiff)

  if [ ${#d} -ge 1 ]; then
    echo -e "${red}FAILED${nc} - $input"
    echo ""
    echo "$d"

    ret=1
  fi
}

red='\033[0;31m'
nc='\033[0m' # No Color

for d in test/*/ ; do
  run_test $d
done

exit $ret